// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Schema;

#nullable disable

namespace Schema.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Schema.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Schema.Models.UserNetworkInfo", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("IpAddressBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ip_address_bytes");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.HasKey("UserId")
                        .HasName("pk_users_network_info");

                    b.ToTable("users_network_info", (string)null);
                });

            modelBuilder.Entity("Schema.Models.UserNetworkInfo", b =>
                {
                    b.HasOne("Schema.Models.User", "User")
                        .WithOne("UserNetworkInfo")
                        .HasForeignKey("Schema.Models.UserNetworkInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_network_info_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Schema.Models.User", b =>
                {
                    b.Navigation("UserNetworkInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
